// <auto-generated />
using System;
using Hart.MCP.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hart.MCP.Api.Migrations
{
    [DbContext(typeof(HartDbContext))]
    [Migration("20251225120254_AddMetadataAndOptimizations")]
    partial class AddMetadataAndOptimizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hart.MCP.Core.Entities.Atom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AtomType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("atom_type");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(GeometryZM, 0)")
                        .HasColumnName("geom");

                    b.Property<long>("HilbertHigh")
                        .HasColumnType("bigint")
                        .HasColumnName("hilbert_high");

                    b.Property<long>("HilbertLow")
                        .HasColumnType("bigint")
                        .HasColumnName("hilbert_low");

                    b.Property<bool>("IsConstant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_constant");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.PrimitiveCollection<int[]>("Multiplicities")
                        .HasColumnType("integer[]")
                        .HasColumnName("multiplicities");

                    b.PrimitiveCollection<long[]>("Refs")
                        .HasColumnType("bigint[]")
                        .HasColumnName("refs");

                    b.Property<int?>("SeedType")
                        .HasColumnType("integer")
                        .HasColumnName("seed_type");

                    b.Property<long?>("SeedValue")
                        .HasColumnType("bigint")
                        .HasColumnName("seed_value");

                    b.HasKey("Id");

                    b.HasIndex("AtomType");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.HasIndex("IsConstant");

                    b.HasIndex("Metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "GIN");

                    b.HasIndex("Refs");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Refs"), "GIN");

                    b.HasIndex("SeedValue");

                    b.HasIndex("HilbertHigh", "HilbertLow");

                    b.ToTable("atom", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
