// <auto-generated />
using Hart.MCP.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hart.MCP.Api.Migrations
{
    [DbContext(typeof(HartDbContext))]
    [Migration("20251225223017_ThreeTableSchema")]
    partial class ThreeTableSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hart.MCP.Core.Entities.Composition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry(GeometryZM, 0)")
                        .HasColumnName("geom");

                    b.Property<decimal>("HilbertHigh")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("hilbert_high");

                    b.Property<decimal>("HilbertLow")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("hilbert_low");

                    b.Property<long?>("TypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("Geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.HasIndex("TypeId");

                    b.HasIndex("HilbertHigh", "HilbertLow");

                    b.ToTable("composition", (string)null);
                });

            modelBuilder.Entity("Hart.MCP.Core.Entities.Constant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geometry(PointZM, 0)")
                        .HasColumnName("geom");

                    b.Property<decimal>("HilbertHigh")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("hilbert_high");

                    b.Property<decimal>("HilbertLow")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("hilbert_low");

                    b.Property<int>("SeedType")
                        .HasColumnType("integer")
                        .HasColumnName("seed_type");

                    b.Property<long>("SeedValue")
                        .HasColumnType("bigint")
                        .HasColumnName("seed_value");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("Geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.HasIndex("HilbertHigh", "HilbertLow");

                    b.HasIndex("SeedType", "SeedValue");

                    b.ToTable("constant", (string)null);
                });

            modelBuilder.Entity("Hart.MCP.Core.Entities.Relation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChildCompositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("child_composition_id");

                    b.Property<long?>("ChildConstantId")
                        .HasColumnType("bigint")
                        .HasColumnName("child_constant_id");

                    b.Property<long>("CompositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("composition_id");

                    b.Property<int>("Multiplicity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("multiplicity");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("ChildCompositionId");

                    b.HasIndex("ChildConstantId");

                    b.HasIndex("CompositionId");

                    b.HasIndex("CompositionId", "Position")
                        .IsUnique();

                    b.ToTable("relation", (string)null);
                });

            modelBuilder.Entity("Hart.MCP.Core.Entities.Composition", b =>
                {
                    b.HasOne("Hart.MCP.Core.Entities.Composition", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Hart.MCP.Core.Entities.Relation", b =>
                {
                    b.HasOne("Hart.MCP.Core.Entities.Composition", "ChildComposition")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("ChildCompositionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hart.MCP.Core.Entities.Constant", "ChildConstant")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("ChildConstantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hart.MCP.Core.Entities.Composition", "Composition")
                        .WithMany("OutgoingRelations")
                        .HasForeignKey("CompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildComposition");

                    b.Navigation("ChildConstant");

                    b.Navigation("Composition");
                });

            modelBuilder.Entity("Hart.MCP.Core.Entities.Composition", b =>
                {
                    b.Navigation("IncomingRelations");

                    b.Navigation("OutgoingRelations");
                });

            modelBuilder.Entity("Hart.MCP.Core.Entities.Constant", b =>
                {
                    b.Navigation("IncomingRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
