[tool.ruff]
line-length = 88
target-version = "py311"
exclude = [
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    ".git",
    ".vscode"
]

[tool.ruff.lint]
select = ["E", "F", "B"]
ignore = ["E501"]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"